// icon
export { ReactComponent as IcApplyCheckDark } from './ic_apply_check_dark.svg'
export { ReactComponent as IcApplyChecklight } from './ic_apply_check_light.svg'
export { ReactComponent as IcArrowDownDark } from './ic_arrow_down_dark.svg'
export { ReactComponent as IcArrowDownLight } from './ic_arrow_down_light.svg'
export { ReactComponent as IcArrowRightDark } from './ic_arrow_right_dark.svg'
export { ReactComponent as IcArrowRightLight } from './ic_arrow_right_light.svg'
export { ReactComponent as IcBackDark } from './ic_back_dark.svg'
export { ReactComponent as IcBackLight } from './ic_back_light.svg'
export { ReactComponent as IcCancelDark } from './ic_cancel_dark.svg'
export { ReactComponent as IcCancelLight } from './ic_cancel_light.svg'
export { ReactComponent as IcCheckMiniDark } from './ic_check_mini_dark.svg'
export { ReactComponent as IcCheckMiniLight } from './ic_check_mini_light.svg'
export { ReactComponent as IcDownArrow } from './ic_down_arrow.svg'
export { ReactComponent as IcHeartDark } from './ic_heart_dark.svg'
export { ReactComponent as IcHeartLight } from './ic_heart_light.svg'
export { ReactComponent as IcMenuDark } from './ic_menu_dark.svg'
export { ReactComponent as IcMenuLight } from './ic_menu_light.svg'
export { ReactComponent as IcSearchDark } from './ic_search_dark.svg'
export { ReactComponent as IcSearchLight } from './ic_search_light.svg'

// brush
export { ReactComponent as IcBrushBold } from './ic_brush_bold.svg'
export { ReactComponent as IcBrushLight } from './ic_brush_light.svg'
export { ReactComponent as IcBrushMedium } from './ic_brush_medium.svg'
export { ReactComponent as IcBrushSelectedBold } from './ic_brush_selected_bold.svg'
export { ReactComponent as IcBrushSelectedLight } from './ic_brush_selected_light.svg'
export { ReactComponent as IcBrushSelectedMedium } from './ic_brush_selected_medium.svg'

// color
export { ReactComponent as IcColorBlack } from './ic_color_black.svg'
export { ReactComponent as IcColorBlackSelected } from './ic_color_black_selected.svg'
export { ReactComponent as IcColorBlue } from './ic_color_blue.svg'
export { ReactComponent as IcColorBlueSelected } from './ic_color_blue_selected.svg'
export { ReactComponent as IcColorRainbow } from './ic_color_rainbow.svg'
export { ReactComponent as IcColorRainbowSelected } from './ic_color_rainbow_selected.svg'
export { ReactComponent as IcColorRed } from './ic_color_red.svg'
export { ReactComponent as IcColorRedSelected } from './ic_color_red_selected.svg'
export { ReactComponent as IcColorYellow } from './ic_color_yellow.svg'
export { ReactComponent as IcColorYellowSelected } from './ic_color_yellow_selected.svg'

// etc
export { ReactComponent as IcFinish } from './ic_finish.svg'
export { ReactComponent as ImgLogoDark } from './img_logo_dark.svg'
export { ReactComponent as ImgLogoLight } from './img_logo_light.svg'
export { ReactComponent as ImgHome } from './img_home.svg'
